config/routes.rb
Rails.application.routes.draw do
  resources :challenges do
    scope module: :challenges do
      resources :run_tests, only: [:create]
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "challenges#index", as: :authenticated_user_root
  end
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_rich_text :description
  has_one_attached :test_file
  has_many :user_challenges
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_challenges
end

app/models/user_challenge.rb
class UserChallenge < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
  enum status: {
    in_progress: 0,
    completed: 1
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/challenges/run_tests_controller.rb
require "minitest/autorun"

class BroadcastLiveResults
  attr_reader :output

  def initialize(challenge, output=STDOUT) 
    @output= output
    @challenge = challenge
  end

  def some_callback(content)
    @challenge.broadcast_update_to(@challenge, target: "results", html: content.join )
  end 

  def method_missing(method_name,*args,**kwargs,&block) 
     if @output.respond_to?(method_name) 
       some_callback(args)
       @output.public_send(method_name,*args,**kwargs,&block) 
     else 
       super
     end 
  end 

  def respond_to_missing?(method_name, include_private = false)
    @output.respond_to?(method_name, include_private) || super
  end
end

module Challenges
  class RunTestsController < ApplicationController
    def create
      @challenge = Challenge.find(params[:challenge_id])
      @user_challenge = @challenge.user_challenges.find_or_create_by(user_id: current_user.id)
      @user_challenge.update(code: params[:code])
      $stdout = BroadcastLiveResults.new(@challenge)
      test_class = Class.new(Minitest::Test)
      test_class.class_eval(@challenge.test_file.download)
      test_instance = test_class.new("Challenge#{@challenge.id}Test")
      eval(params[:code])
      result = Minitest.run([test_instance])
      if result
        @user_challenge.update(status: :completed)
        @challenge.broadcast_append_to(@challenge, target: "results", partial: "challenges/complete")
      else
        @challenge.broadcast_append_to(@challenge, target: "results", partial: "challenges/failed")
      end
    end
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: %i[ show edit update destroy ]

  # GET /challenges or /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1 or /challenges/1.json
  def show
    @user_challenge = current_user.user_challenges.find_by(challenge_id: @challenge.id)
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges or /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        CreateTestFileJob.perform_later(@challenge.id)
        format.html { redirect_to challenge_url(@challenge), notice: "Challenge was successfully created." }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1 or /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        CreateTestFileJob.perform_later(@challenge.id)
        format.html { redirect_to challenge_url(@challenge), notice: "Challenge was successfully updated." }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1 or /challenges/1.json
  def destroy
    @challenge.destroy!

    respond_to do |format|
      format.html { redirect_to challenges_url, notice: "Challenge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def challenge_params
      params.require(:challenge).permit(:description, :tests)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/challenges/_challenge.html.erb
<div id="<%= dom_id challenge %>" class="p-2 bg-gray-300">
  <div class="text-lg">
    <%= challenge.description %>
  </div>
  <% if action_name != "show" %>
    <%= link_to "Start Challenge", challenge, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <% end %>
</div>

app/views/challenges/_code_editer.html.erb
<%= form_with url: challenge_run_tests_path(challenge) do |f| %>
  <div class="flex flex-col gap-4">
    <%= f.label :code %>
    <%= f.text_area :code, class: "w-full min-h-[500px]", style: "resize:none;", value: @user_challenge&.code %>
  </div>
  <br/>
  <%= f.submit "Run Tests", class: "px-3 py-2 rounded-lg bg-blue-500 text-blue-100 cursor-pointer" %>
<% end %>

app/views/challenges/_complete.html.erb
<div class="bg-green-500 text-green-100 text-2xl">
  You solved the challenge!!
</div>

app/views/challenges/_failed.html.erb
<div class="bg-red-500 text-red-100 text-2xl">
  The tests failed! Try a new solution
</div>

app/views/challenges/_form.html.erb
<%= form_with(model: challenge, class: "contents") do |form| %>
  <% if challenge.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
        <% challenge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :tests %>
    <%= form.text_area :tests, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full min-h-[300px]", style: "resize: none;" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing challenge</h1>

  <%= render "form", challenge: @challenge %>

  <%= link_to "Show this challenge", @challenge, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to challenges", challenges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/challenges/index.html.erb
<div class="w-full max-w-7xl mx-auto mt-16">

  <div class="flex items-center">
    <h1 class="font-bold text-4xl">Challenges</h1>
  </div>

  <div id="challenges" class="min-w-full grid grid-cols-3 gap-4 mt-4">
    <%= render @challenges %>
  </div>
</div>

app/views/challenges/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New challenge</h1>

  <%= render "form", challenge: @challenge %>

  <%= link_to "Back to challenges", challenges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/challenges/show.html.erb
<%= turbo_stream_from @challenge %>

<div class="mx-auto max-w-7xl w-full flex flex-col pt-16">
  <%= render @challenge %>
  <%= render "code_editer", challenge: @challenge, user_challenge: @user_challenge %>

  <div id="results">
    <% if @user_challenge&.completed? %>
      <%= render "complete" %>
    <% end %>
  </div>
  <br/>
  <%= link_to "Back to challenges", challenges_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingChallenges</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="w-full flex flex-col items-center">
  <h1 class="font-bold text-4xl text-center">Cool Coding Challenges</h1>
  <p class="text-center">Some awesome coding challenges</p>
  <%= link_to "Sign in", new_user_session_path, class: "p-2 rounded-lg w-32 text-center bg-indigo-500 text-indigo-100" %>
</div>